# -*- coding: utf-8 -*-
import os
out = '/Users/liuqi/code/tplink/mvp/html/02_profile.html'
lines = []
lines.append('<!DOCTYPE html><html lang="zh-CN"><head><meta charset="UTF-8">')
lines.append('<meta name="viewport" content="width=390, initial-scale=1.0">')
lines.append('<title>我的灵魂档案 · SoulMatch</title><style>')
lines.append('* { margin:0; padding:0; box-sizing:border-box; -webkit-font-smoothing:antialiased; }')
lines.append('body { width:390px; height:844px; overflow:hidden; font-family:-apple-system,"PingFang SC",sans-serif; background:#F2F2F7; display:flex; flex-direction:column; }')
lines.append('.status-bar { width:390px; height:54px; background:#6C5CE7; display:flex; align-items:center; justify-content:space-between; padding:14px 20px 0 20px; flex-shrink:0; }')
lines.append('.status-time { font-size:15px; font-weight:600; color:#fff; }')
lines.append('.status-icons { display:flex; align-items:center; gap:6px; }')
lines.append('.nav-bar { background:#6C5CE7; padding:8px 20px 18px 20px; flex-shrink:0; }')
lines.append('.nav-title { font-size:34px; font-weight:700; color:#fff; letter-spacing:-0.5px; }')
lines.append('.scroll-content { flex:1; overflow-y:auto; -webkit-overflow-scrolling:touch; }')
lines.append('.scroll-content::-webkit-scrollbar { display:none; }')
lines.append('.hero-card { background:linear-gradient(135deg,#6C5CE7 0%,#a29bfe 100%); padding:24px 20px 28px 20px; position:relative; overflow:hidden; }')
lines.append('.hero-card::before { content:""; position:absolute; top:-40px; right:-40px; width:160px; height:160px; border-radius:50%; background:rgba(255,255,255,0.08); }')
lines.append('.hero-card::after { content:""; position:absolute; bottom:-30px; left:-20px; width:120px; height:120px; border-radius:50%; background:rgba(255,255,255,0.06); }')
lines.append('.hero-top { display:flex; align-items:center; gap:16px; margin-bottom:16px; }')
lines.append('.avatar { width:64px; height:64px; border-radius:50%; background:rgba(255,255,255,0.25); display:flex; align-items:center; justify-content:center; font-size:26px; font-weight:700; color:#fff; border:2.5px solid rgba(255,255,255,0.5); flex-shrink:0; position:relative; z-index:1; }')
lines.append('.hero-info { position:relative; z-index:1; }')
lines.append('.hero-name { font-size:22px; font-weight:700; color:#fff; margin-bottom:4px; }')
lines.append('.hero-sub { font-size:14px; color:rgba(255,255,255,0.85); font-weight:500; }')
lines.append('.hero-tags { display:flex; gap:8px; flex-wrap:wrap; position:relative; z-index:1; margin-top:4px; }')
lines.append('.hero-tag { background:rgba(255,255,255,0.2); border:1px solid rgba(255,255,255,0.35); border-radius:20px; padding:5px 12px; font-size:12px; font-weight:600; color:#fff; }')
lines.append('.section-card { background:#fff; border-radius:16px; margin:12px 16px 0 16px; padding:18px 16px; box-shadow:0 2px 8px rgba(0,0,0,0.06); }')
lines.append('.section-title { font-size:13px; font-weight:700; color:#8E8E93; text-transform:uppercase; letter-spacing:0.7px; margin-bottom:12px; }')
lines.append('.analysis-text { font-size:15px; color:#3A3A3C; line-height:1.75; }')
lines.append('.trait-row { margin-bottom:13px; } .trait-row:last-child { margin-bottom:0; }')
lines.append('.trait-labels { display:flex; justify-content:space-between; margin-bottom:5px; }')
lines.append('.trait-left { font-size:13px; font-weight:600; color:#1C1C1E; } .trait-right { font-size:13px; color:#C7C7CC; }')
lines.append('.trait-bar-bg { width:100%; height:8px; background:#F2F2F7; border-radius:4px; overflow:hidden; }')
lines.append('.trait-bar-fill { height:100%; background:linear-gradient(90deg,#6C5CE7,#a29bfe); border-radius:4px; }')
lines.append('.trait-pct { font-size:12px; color:#6C5CE7; font-weight:600; text-align:right; margin-top:3px; }')
lines.append('.match-item { display:flex; align-items:flex-start; gap:10px; margin-bottom:10px; font-size:15px; color:#3A3A3C; line-height:1.5; }')
lines.append('.match-item:last-child { margin-bottom:0; } .mi-yes { color:#00B894; flex-shrink:0; margin-top:2px; } .mi-no { color:#FF3B30; flex-shrink:0; margin-top:2px; }')
lines.append('.bottom-cta { padding:12px 16px 10px 16px; background:#F2F2F7; flex-shrink:0; }')
lines.append('.btn-match { width:100%; height:52px; background:#00B894; border:none; border-radius:16px; color:#fff; font-size:17px; font-weight:600; font-family:inherit; cursor:pointer; display:flex; align-items:center; justify-content:center; gap:8px; box-shadow:0 4px 16px rgba(0,184,148,0.35); }')
lines.append('.tab-bar { height:83px; background:#fff; border-top:0.5px solid rgba(0,0,0,0.12); display:flex; align-items:flex-start; padding-top:10px; flex-shrink:0; }')
lines.append('.tab-item { flex:1; display:flex; flex-direction:column; align-items:center; gap:4px; cursor:pointer; }')
lines.append('.tab-label { font-size:10px; color:#8E8E93; font-weight:500; } .tab-item.active .tab-label { color:#6C5CE7; }')
lines.append('.tab-icon { color:#8E8E93; } .tab-item.active .tab-icon { color:#6C5CE7; }')
lines.append('</style></head><body>')
