#!/bin/bash

echo "=========================================="
echo "Cookie 更新助手"
echo "=========================================="
echo ""
echo "请按照以下步骤操作："
echo ""
echo "1. 在浏览器中访问 https://www.xiaohongshu.com"
echo "2. 登录你的小红书账号"
echo "3. 安装 EditThisCookie 插件（如果还没有）"
echo "4. 点击插件图标，点击'导出'按钮"
echo "5. Cookie 会复制到剪贴板"
echo "6. 将 Cookie 粘贴到文件："
echo "   /home/ecs-user/cookies/cookies (6).json"
echo ""
echo "其他平台 Cookie 文件："
echo "  - 微博：cookies (7).json"
echo "  - 抖音：cookies (8).json"
echo "  - 网易云：cookies (9).json"
echo "  - 豆瓣：cookies (10).json"
echo "  - 知乎：cookies (11).json"
echo ""
echo "更新完成后，运行测试："
echo "  cd /home/ecs-user/tplink-app/tplink/soul_profile_app"
echo "  npx tsx test-xhs-scrape.ts"
echo ""
echo "=========================================="
